//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        public int Reception_id { get; set; }
        public int Doctor_Id { get; set; }
        public int Specialty_Id { get; set; }
        public int Patient_Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public string Type { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Specialty Specialty { get; set; }
    }
}
